### ISSUE TITLE
Syncing Tasks

### ISSUE THREAD

**Issue by paavo** [mikerourke/transfermyti.me#12]
We'd love to have Tasks (related to a Project) synced from Toogl to Clockify.

**Comment by mikerourke** [comment]
I believe I have it setup for the most part, I'm just unable to test it because I don't have a Toggl premium account (required for tasks). I'll take a look at the code. I've fumbled the ball on keeping the app up to date, so I'm sure there have been API changes since I last worked on it. I'll let you know when I have something ready to test.

**Comment by paavo** [comment]
Thanks for your work @mikerourke !
Just tell me if you have something to test!

Maybe signing up for a free trial of Toggl helps?

**Comment by mikerourke** [comment]
This should work. I added the functionality required to transfer tasks, I'm unable to test because I have a free Toggl membership.
